dependencies:
- alias: expose
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.89
- alias: cleanup
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.89
- name: ico
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.152
- name: main
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.3
- name: pay-admin
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: space-admin
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.3
- name: space-web
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.6
- name: trade-admin
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.3
- name: ws
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.21
