dependencies:
- name: card-admin
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.17
- name: card-api
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.13
- name: card-web
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.14
- alias: cleanup
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.89
- alias: expose
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.89
- name: ico
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.155
- name: main
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.3
- name: pay-admin
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.15
- name: pay-api
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.20
- name: pay-web
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.14
- name: space-admin
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.41
- name: space-api
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.43
- name: space-web
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.26
- name: trade-admin
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.22
- name: trade-api
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.34
- name: trade-web
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.47
- name: ws
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.38
