dependencies:
- alias: expose
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.89
- alias: cleanup
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.89
- name: ico
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.153
- name: main
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.3
- name: pay-admin
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.5
- name: space-admin
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.5
- name: space-api
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.5
- name: space-web
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.8
- name: trade-admin
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.11
- name: trade-api
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.3
- name: trade-web
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.5
- name: ws
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.21
