dependencies:
- name: card-admin
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.7
- name: card-api
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.4
- name: card-web
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.2
- alias: cleanup
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.89
- alias: expose
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.89
- name: ico
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.155
- name: main
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.3
- name: pay-admin
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.9
- name: pay-api
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.8
- name: pay-web
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.6
- name: space-admin
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.18
- name: space-api
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.14
- name: space-web
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.10
- name: trade-admin
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.15
- name: trade-api
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.6
- name: trade-web
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.9
- name: ws
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.25
